### ISSUE TITLE
Errors with Node 4 (v0.2.1)

### ISSUE THREAD

**Issue by ewindisch** [iopipe/serverless-plugin-iopipe#19]
```
$ SLS_DEBUG=* sls
 
  Syntax Error -------------------------------------------
 
     Unexpected token =
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:98:22
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:97:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:124:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:93:10)
    at /usr/local/lib/node_modules/serverless/lib/Serverless.js:64:28
From previous event:
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:15:28
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 linux
     Node Version:       4.2.6
     Serverless Version: 1.14.0
 
```

running   serverless-plugin-iopipe 0.2.1

**Comment by coreylight** [comment]
Fixed with #21
