### ISSUE TITLE
connect ECONNREFUSED 0.0.0.0:443 Error

### ISSUE THREAD

**Issue by rad182** [iopipe/serverless-plugin-iopipe#38]
Hi I'm currently having this error for `sls deploy`

```
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: serverless-plugin-iopipe: Wrapping your functions with IO|...

  Error --------------------------------------------------

  connect ECONNREFUSED 0.0.0.0:443

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: connect ECONNREFUSED 0.0.0.0:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.1.4
     Serverless Version:     1.21.1
```

Any idea? followed the serverless.yaml example

**Comment by rad182** [comment]
resolved by adding these fields under `custom` to avoid sending network calls.
```
iopipeNoVerify: true
iopipeNoUpgrade: true
iopipeNoStats: true
```
thanks to @pselle
